repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.13
  hooks:
  - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.0
  hooks:
  - id: ruff-check
    args: [ --fix ]
  - id: ruff-format
- repo: local
  hooks:
  - id: doctest
    name: run doctest on all files
    entry: make doctest
    language: system
    pass_filenames: false

